### ISSUE TITLE
Stryker dashboard returned an unexpected response code: 400.

### ISSUE THREAD

**Issue by terabytesoftw** [stryker-mutator/stryker-dashboard#346]
PHP: 8.2.
PHPUNIT: 10.1.3
INFECTION: 0.26.21

```JSON
{"name":"BAD_REQUEST","message":"Invalid report. data must have required property 'schemaVersion'","status":400,"errors":[],"stack":"BAD_REQUEST: Invalid report. data must have required property 'schemaVersion'\n    at ReportsController.verifyRequiredPutReportProperties (file:///app/node_modules/@stryker-mutator/dashboard-backend/dist/src/api/ReportsController.js:98:23)\n    at ReportsController.update (file:///app/node_modules/@stryker-mutator/dashboard-backend/dist/src/api/ReportsController.js:35:14)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
```

**Comment by rouke-broersma** [comment]
@terabytesoftw did your problem solve itself or was this closed by accident?

**Comment by terabytesoftw** [comment]
> @terabytesoftw did your problem solve itself or was this closed by accident?

Thks, i solved it by activating and deactivating it from the board.
